/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package timetableis.view;

import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JList;

/**
 *
 * @author upeksha
 */
public class ModuleManagerWindow extends javax.swing.JPanel {
    private DefaultListModel<String> listSubjects = new DefaultListModel<>();
    /**
     * Creates new form subjectManagerPanel
     */
    public ModuleManagerWindow() {
        
        initComponents();
        jListsubjects.setModel(listSubjects);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
    public void update() {        
        refreshList();
    }

    public void refreshList() {

        listSubjects.clear();
        List<Module> list = ListCollection.getSubjects();
        
        for (int i = 0; i < list.size(); i++) {
            listSubjects.addElement(list.get(i).toString());
            System.out.println("xzdsd "+listSubjects.getElementAt(i).toString());
        }

    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        subMtitlePanel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        subjectCodeLabel = new javax.swing.JLabel();
        subjectCodeText = new javax.swing.JTextField();
        subjectNameText = new javax.swing.JTextField();
        subjectNameLabel = new javax.swing.JLabel();
        separator2 = new javax.swing.JSeparator();
        subjectAddBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        subjectRemoveBtn = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jListsubjects = new javax.swing.JList();
        separator1 = new javax.swing.JSeparator();

        jLabel2.setText("jLabel2");

        jTextField2.setText("jTextField2");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        subMtitlePanel.setFont(new java.awt.Font("Ubuntu", 2, 18)); // NOI18N
        subMtitlePanel.setText("Subject Manager Panel");

        subjectCodeLabel.setText("Subject Code ");

        subjectNameLabel.setText("Subject Name");

        subjectAddBtn.setText("Add");
        subjectAddBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subjectAddBtnActionPerformed(evt);
            }
        });

        jLabel4.setText("Currently Available Subjects");

        subjectRemoveBtn.setText("Remove");
        subjectRemoveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subjectRemoveBtnActionPerformed(evt);
            }
        });

        jScrollPane3.setViewportView(jListsubjects);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(subjectCodeLabel)
                .addGap(18, 18, 18)
                .addComponent(subjectCodeText, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 307, Short.MAX_VALUE)
                .addComponent(subjectNameLabel)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(subjectAddBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(subjectNameText))
                .addContainerGap())
            .addComponent(separator2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(subjectRemoveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(subjectCodeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(subjectNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(subjectCodeLabel)
                    .addComponent(subjectNameLabel))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(subjectAddBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(separator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel4))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(subjectRemoveBtn)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(subMtitlePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(separator1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(subMtitlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(separator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void subjectAddBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subjectAddBtnActionPerformed
        if(subjectNameText.getText()!=null && subjectCodeText.getText()!=null){
            Module s = new Module(subjectNameText.getText(),subjectCodeText.getText());

            if (!ListCollection.getSubjects().contains(s.toString())) {
                System.out.println("added subject" + s.getCode());
                ListCollection.getSubjects().add(s);
            }

            refreshList();
            
            subjectNameText.setText("");
            subjectCodeText.setText("");
        }
    }//GEN-LAST:event_subjectAddBtnActionPerformed

    private void subjectRemoveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subjectRemoveBtnActionPerformed
        int index = jListsubjects.getSelectedIndex();
        if (index >= 0) {
            if(!listSubjects.isEmpty()){
                String sub = listSubjects.get(index);
                ListCollection.getSubjects().remove(ListCollection.getSubjects().indexOf(sub));
                listSubjects.remove(index);
            }
            else{
                jListsubjects.removeAll();
            }

        }      
    }//GEN-LAST:event_subjectRemoveBtnActionPerformed

    public void updateSubjectJlist(List<Module> subjects){
        for(int i=0;i<subjects.size();i++){
            listSubjects.addElement(subjects.get(i).getName()+":"+subjects.get(i).getCode());
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JList jListsubjects;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JSeparator separator1;
    private javax.swing.JSeparator separator2;
    private javax.swing.JLabel subMtitlePanel;
    private javax.swing.JButton subjectAddBtn;
    private javax.swing.JLabel subjectCodeLabel;
    private javax.swing.JTextField subjectCodeText;
    private javax.swing.JLabel subjectNameLabel;
    private javax.swing.JTextField subjectNameText;
    private javax.swing.JButton subjectRemoveBtn;
    // End of variables declaration//GEN-END:variables
}
