/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package timetableis.view;

import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author GAYAN
 */
public class TimeTables extends javax.swing.JPanel {

    /**
     * Creates new form TimeTables
     */
    public TimeTables() {
        initComponents();
        updateSemesters();
        updateLecturerNames();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        semesterTable = new javax.swing.JTable();
        semesters = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        showSemesterTable = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lecturerNames = new javax.swing.JComboBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        lecturerTable = new javax.swing.JTable();
        showLecturerTable = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(680, 480));
        setRequestFocusEnabled(false);

        semesterTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Monday", "Tuesday", "Wednesday", "Thursday", "Friday"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        semesterTable.setRowHeight(30);
        jScrollPane1.setViewportView(semesterTable);

        jLabel1.setText("Semester");

        showSemesterTable.setText("Show");
        showSemesterTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showSemesterTableActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 635, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(semesters, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(showSemesterTable, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(semesters, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(showSemesterTable))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Semester", jPanel1);

        jLabel2.setText("Name Of Lecturer");

        lecturerTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Monday", "Tuesday", "Wednesday", "Thursday", "Friday"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        lecturerTable.setRowHeight(30);
        jScrollPane2.setViewportView(lecturerTable);

        showLecturerTable.setText("Show");
        showLecturerTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showLecturerTableActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(lecturerNames, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 151, Short.MAX_VALUE)
                        .addComponent(showLecturerTable, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(showLecturerTable)
                    .addComponent(lecturerNames, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Lecturer", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(90, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void showSemesterTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showSemesterTableActionPerformed
         for (int i = 0; i < 5; i++) {
            for (int j = 0; j < 8; j++) {
                 semesterTable.setValueAt("", j, i);
            }
        }
        
        Semester cls= ListCollection.getClasses().get(semesters.getSelectedIndex());
        List<Module> sublist=new ArrayList<>();
        List<Module> allsubs=ListCollection.getSubjects();
        
        for (int i = 0; i < allsubs.size(); i++) {
            if(allsubs.get(i).getFixedClass()!=null && allsubs.get(i).getFixedClass().equals(cls)){
                sublist.add(allsubs.get(i));
            }
        }
        
        Module s;
        for (int i = 0; i <sublist.size() ; i++) {
            s=sublist.get(i);         
            int color=s.getColor()-1;
            if(color>=0){
                int x=color%5;
                int y=(color/5)*2;
                semesterTable.setValueAt(s.getName(), y, x);
                semesterTable.setValueAt("do", y+1, x);
            }
        }
    }//GEN-LAST:event_showSemesterTableActionPerformed

    private void showLecturerTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showLecturerTableActionPerformed
        for (int i = 0; i < 5; i++) {
            for (int j = 0; j < 8; j++) {
                 lecturerTable.setValueAt("", j, i);
            }
        }
        
        Lecturer t= ListCollection.getTeachers().get(lecturerNames.getSelectedIndex());
        List<Module> sublist=t.getSubjects();
        Module s;        
        
        for (int i = 0; i <sublist.size() ; i++) {
           
            s=sublist.get(i);         
            int color=s.getColor()-1;
            if(color>=0){
                int x=color%5;
                int y=(color/5)*2;
                lecturerTable.setValueAt(s.getName(), y, x);
                lecturerTable.setValueAt("do", y+1, x);
            }
        }
    }//GEN-LAST:event_showLecturerTableActionPerformed
    
     public void updateSemesters(){
        List<Semester> classes=ListCollection.getClasses();
        
        for(int i=0;i<classes.size();i++){
            semesters.addItem(classes.get(i).getName());
        }
    }
     
    public void updateLecturerNames(){
        List<Lecturer> lecturers=ListCollection.getTeachers();
        
        for(int i=0;i<lecturers.size();i++){
            lecturerNames.addItem(lecturers.get(i).getName());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JComboBox lecturerNames;
    private javax.swing.JTable lecturerTable;
    private javax.swing.JTable semesterTable;
    private javax.swing.JComboBox semesters;
    private javax.swing.JButton showLecturerTable;
    private javax.swing.JButton showSemesterTable;
    // End of variables declaration//GEN-END:variables
}
